### ISSUE TITLE
props.alt returns null

### ISSUE THREAD

**Issue by dfosco** [christianalfoni/markdown-to-react-components#23]
Hi there,

I'm trying to display alt text that comes from image tags in my markdown, but after passing them through MTRC, it returns `null`. I've confirmed they're coming in before processing the markdown... somehow the `img` function in the configuration just can't see it.

Not sure if anyone has reported this yet — I can send more information about the bug and my setup if needed be. Thanks!

**Comment by christianalfoni** [comment]
This repo is DEPRECATED, could you try using: https://github.com/cerebral/marksy? Or create an issue there if it still happens :)

**Comment by dfosco** [comment]
Cool! Will try to convert to marksy in the next few days and see if it still happens, thanks :+1:
