### ISSUE TITLE
MTRC is returning plain objects, not react components

### ISSUE THREAD

**Issue by CodyReichert** [christianalfoni/markdown-to-react-components#26]
Hey, thanks for the really cool library! I'm trying to integrate this into my app, but am hitting an issue and I'm not sure what's causing it.

When I run a markdown string through MRTC, I'm getting back a list of objects that are _not_ react components. Basically, this is all I have so far:

```js
const MTRC = require('markdown-to-react-components')
MTRC.configure({})

const md = "# Header text"
const components = MTRC(md)

console.log(components.tree)
```

...however, the `.tree` I'm getting back is an array of 'plain' objects, not React components.

```json
"{
  "type": "p",
  "key": "1",
  "ref": null,
  "props": {
    "children": [
      "Header text",
    ]
  },
  "_owner": null,
  "_store": {}
}"
```

When I run the example from this repo, the objects returned from `MTRC` _are_ react components (eg, with the `$$typeof` key and everything else).

The only thing I can think that might be relevant is that I'm using React 15, while this library is using React 0.14. It probably has something to with this.

Any tips or pointers for getting around this?

**Comment by christianalfoni** [comment]
@CodyReichert This seems weird, but this repo just got DEPRECATED in favor of: https://github.com/cerebral/marksy. Could you try that out? :-)
