### ISSUE TITLE
Blockquote generates double `p`

### ISSUE THREAD

**Issue by bebraw** [christianalfoni/markdown-to-react-components#8]
Demo:

``` javascript
var React = require('react');
var ReactDOM = require('react-dom/server');
var MTRC = require('markdown-to-react-components');

console.log(ReactDOM.renderToStaticMarkup(
  React.createElement('div', {}, MTRC('> Demo').tree))
);
```

``` json
{
  "name": "mtrc-demo",
  "version": "1.0.0",
  "description": "",
  "main": "demo.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "markdown-to-react-components": "^0.1.4",
    "react": "^0.14.3",
    "react-dom": "^0.14.3"
  }
}
```

This yields:

``` bash
Warning: Each child in an array or iterator should have a unique "key" prop. Check the top-level render call using <div>. See https://fb.me/react-warning-keys for more information.
Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>. See p > ... > p.
<div><blockquote><p><p>Demo</p></p></blockquote></div>
```

There shouldn't be a `p` inside `p`.

**Comment by christianalfoni** [comment]
Hm, this only happens when the blockquote is the first thing in the markdown string. So that is handled differently by the "marked" converter... which I suppose it should not.

You agree it is a "marked" bug?

**Comment by bebraw** [comment]
I'm not sure. Demo:

``` javascript
const marked = require('marked');

console.log(marked('> Demo'));
```

gives

``` bash
<blockquote>
<p>Demo</p>
</blockquote>
```

which looks ok to me.

The input is the same. It's possible I'm missing some nuance here. MTRC goes through marked parser after all so maybe the demo needs to be expanded.

**Comment by christianalfoni** [comment]
Hm, I am thinking that maybe we should use the lexer instead: https://github.com/chjj/marked

**Comment by bebraw** [comment]
Yeah. That's a possibility. I know [markdown-it](https://www.npmjs.com/package/markdown-it) is an alternative.

[mdast-react](https://github.com/jjt/mdast-react#2ea3bcd) actually does more or less the same as MTRC but it seems unmaintained at the moment. [Spectacle](https://github.com/FormidableLabs/spectacle) uses the version I linked to.

**Comment by christianalfoni** [comment]
Thanks for the info Juho :-) I need a weekend mini project, looks fun using the lexer to build the components instead. Also seems a lot safer, as I am doing some crazy trickery with shared state between the constructors.

By the end of the weekend I should have something ;-)

**Comment by bebraw** [comment]
Ok, cool. One interesting option would be simply to fork [mdast-react by jjt](https://github.com/jjt/mdast-react#2ea3bcd) and then move from there based on your needs. That could save significant effort.

I also love the fact that there are nice plugins, like [remark-toc](https://github.com/wooorm/remark-toc), for mdast.

**Comment by christianalfoni** [comment]
Hm, does it have any missing features compared to this project? I only built this because I could not find any markdown react projects that actually built react components :-)

**Comment by bebraw** [comment]
It looks somewhat feature complete to me. The only part I'm a little unsure of is highlighting. I guess you'll know better by trying it out. :+1:

**Comment by christianalfoni** [comment]
Okay, let me check it out this weekend. It looks like fun to play around with the lexer thingy. Typical "beer project" :-) But if the other one is feature complete I do not see any reason to have "yet another" markdown to react components project. But good point on highlighting, that is an important feature.

**Comment by wooorm** [comment]
A note about highlighting: remark combined with remark-html has support for injecting HTML by plug-ins, e.g., [mdast-highlight.js](https://github.com/ben-eb/mdast-highlight.js), however, when injecting into a (virtual) DOM on the client it’s often a bad (unsafe) idea due to having to depend on `dangerouslySetInnerHTML`.

It would be better to pass in custom components, e.g., a quick search gave me [react-highlight](https://github.com/akiran/react-highlight). Which, _should_ be possible to use in [mdast-react](https://github.com/mapbox/mdast-react) (and otherwise we should build it!)
