### ISSUE TITLE
Nested bold and italic break rendering

### ISSUE THREAD

**Issue by isTravis** [christianalfoni/markdown-to-react-components#9]
Howdy! Thanks for the great repo - we've found it really useful!

We're running into a bug whenever we have italic nested inside of bold or vice versa.

Any tips for approaching it?

![screen shot 2016-01-02 at 4 14 42 pm](https://cloud.githubusercontent.com/assets/1000455/12076108/16dd82fc-b16c-11e5-85df-da736936e62e.png)

Github markdown seems to work when attempting this:
**bold and _italic_**
_italic and **bold**_

**Comment by christianalfoni** [comment]
I think it is time for a rewrite of the project, using the lexer of "marked", instead of the renderer. That will allow for more granular control of how things are rendered :)
